#!/bin/bash

for ((i=1; i<=5; i++))
do
    case $i in
        1) fruit="Apple" ;;
        2) fruit="Mango" ;;
        3) fruit="Strawberry" ;;
        4) fruit="Orange" ;;
        5) fruit="Banana" ;;
    esac
    echo "FRUIT: $fruit"
done
